language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew :android-segment:test
  - ./gradlew :android-segment:install --stacktrace
  - ./gradlew bintrayUpload

